FROM ghcr.io/marcinmajsc/uosserver:0.0.54-linux-arm64

LABEL org.opencontainers.image.source="https://github.com/marcinmajsc/unifi-os-server"

ENV UOS_SERVER_VERSION="5.0.6"
ENV FIRMWARE_PLATFORM="linux-arm64"

STOPSIGNAL SIGRTMIN+3

COPY uos-entrypoint.sh /root/uos-entrypoint.sh

RUN ["chmod", "+x", "/root/uos-entrypoint.sh"]
ENTRYPOINT ["/root/uos-entrypoint.sh"]
